export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";
export const GET_USER_RESET = "GET_USER_RESET";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const LOGOUT_RESET = "LOGOUT_RESET";

export const SEND_CURRENT_MESSAGE_REQUEST = "SEND_CURRENT_MESSAGE_REQUEST";
export const SEND_CURRENT_MESSAGE_SUCCESS = "SEND_CURRENT_MESSAGE_SUCCESS";
export const SEND_CURRENT_MESSAGE_FAIL = "SEND_CURRENT_MESSAGE_FAIL";
export const SEND_CURRENT_MESSAGE_RESET = "SEND_CURRENT_MESSAGE_RESET";

export const SELECT_FRIEND_MESSAGE_REQUEST = "SELECT_FRIEND_MESSAGE_REQUEST";
export const SELECT_FRIEND_MESSAGE_SUCCESS = "SELECT_FRIEND_MESSAGE_SUCCESS";
export const SELECT_FRIEND_MESSAGE_FAIL = "SELECT_FRIEND_MESSAGE_FAIL";
export const SELECT_FRIEND_MESSAGE_RESET = "SELECT_FRIEND_MESSAGE_RESET";

// SEARCH USER FOR ADD NEW FRIEND
export const SEARCH_USER_REQUEST = "SEARCH_USER_REQUEST";
export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS";
export const SEARCH_USER_FAIL = "SEARCH_USER_FAIL";
export const SEARCH_USER_RESET = "SEARCH_USER_RESET";

export const SEND_FRIEND_REQ_REQUEST = "SEND_FRIEND_REQ_REQUEST";
export const SEND_FRIEND_REQ_SUCCESS = "SEND_FRIEND_REQ_SUCCESS";
export const SEND_FRIEND_REQ_FAIL = "SEND_FRIEND_REQ_FAIL";
export const SEND_FRIEND_REQ_RESET = "SEND_FRIEND_REQ_RESET";

export const ACCEPT_FRIEND_REQ_REQUEST = "ACCEPT_FRIEND_REQ_REQUEST";
export const ACCEPT_FRIEND_REQ_SUCCESS = "ACCEPT_FRIEND_REQ_SUCCESS";
export const ACCEPT_FRIEND_REQ_FAIL = "ACCEPT_FRIEND_REQ_FAIL";
export const ACCEPT_FRIEND_REQ_RESET = "ACCEPT_FRIEND_REQ_RESET";

export const CANCEL_FRIEND_REQ_REQUEST = "CANCEL_FRIEND_REQ_REQUEST";
export const CANCEL_FRIEND_REQ_SUCCESS = "CANCEL_FRIEND_REQ_SUCCESS";
export const CANCEL_FRIEND_REQ_FAIL = "CANCEL_FRIEND_REQ_FAIL";
export const CANCEL_FRIEND_REQ_RESET = "CANCELOVE_FRIEND_REQ_RESET";

export const REMOVE_FRIEND_REQ_REQUEST = "REMOVE_FRIEND_REQ_REQUEST";
export const REMOVE_FRIEND_REQ_SUCCESS = "REMOVE_FRIEND_REQ_SUCCESS";
export const REMOVE_FRIEND_REQ_FAIL = "REMOVE_FRIEND_REQ_FAIL";
export const REMOVE_FRIEND_REQ_RESET = "REMOVE_FRIEND_REQ_RESET";

export const GET_LIST_FRIEND_REQ_REQUEST = "GET_LIST_FRIEND_REQ_REQUEST";
export const GET_LIST_FRIEND_REQ_SUCCESS = "GET_LIST_FRIEND_REQ_SUCCESS";
export const GET_LIST_FRIEND_REQ_FAIL = "GET_LIST_FRIEND_REQ_FAIL";
export const GET_LIST_FRIEND_REQ_RESET = "GET_LIST_FRIEND_REQ_RESET";

